version: '2'

services:
    db:
        image: mysql
        user: "1000:50"
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7-fpm
        user: "1000:50"
        ports:
            - 9000:9000
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ${PHPMYADMIN_ROOT_PATH}:/var/www/phpmyadmin
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - db
            - redis
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf
            - ./logs/nginx/:/var/log/nginx

    redis:
        image: redis:alpine
        ports:
            - 6379:6379
            
#    elk:
#        image: willdurand/elk
#        ports:
#            - 81:80
#        volumes:
#            - ./elk/logstash:/etc/logstash
#            - ./elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - php
#            - nginx
