version: '2'

services:
    db:
        image: mysql
        user: "1000:50"
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/symfony.conf:/etc/nginx/conf.d/symfony.conf
            - ./logs/nginx/:/var/log/nginx
#    elk:
#        image: willdurand/elk
#        ports:
#            - 81:80
#        volumes:
#            - ./elk/logstash:/etc/logstash
#            - ./elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - php
#            - nginx
