version: '2'

services:
    db:
        image: mysql
        user: "1000:50"
        volumes:
            - "./.data/db:/var/lib/mysql"
        command: --innodb_use_native_aio=0
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7-fpm
        user: "1000:50"
        #ports:
        #    - 9000:9000
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ${PHPMYADMIN_ROOT_PATH}:/var/www/phpmyadmin
            - ./logs/symfony:/var/www/symfony/app/logs
        links:
            - db
            - redis
            - elasticsearch
            - beanstalkd
    nginx:
        build: nginx
        ports:
            - 80:80
            - 81:81
            - 82:82
        volumes_from:
            - php
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf
            - ./logs/nginx/:/var/log/nginx

    redis:
        image: redis:alpine
        #ports:
        #    - 6379:6379
        #command: >
        #  --slaveof 10.0.0.2 6379
        #  --requirepass fucksecret
        
    beanstalkd:
        build: beanstalkd
        #ports:
        #    - 11300:11300
        volumes:
            - "./.data/beanstalkd:/var/lib/beanstalkd"

    elasticsearch:
        build: elasticsearch
        # ON HOST MACHINE NEED TO RUN `sudo sysctl -w vm.max_map_count=262144` AND THEN `echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf`
        # ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
        # The default password for the elastic user is changeme
        # image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
        #ports:
        #    - 9200:9200
        volumes:
            - "./.data/esdata:/usr/share/elasticsearch/data"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            
#    elk:
#        image: willdurand/elk
#        ports:
#            - 81:80
#        volumes:
#            - ./elk/logstash:/etc/logstash
#            - ./elk/logstash/patterns:/opt/logstash/patterns
#        volumes_from:
#            - php
#            - nginx
